development:
  clients:
    default:
      database: heroku_r23vsgp4
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: pedro-maciel-test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%=ENV["MONGODB_URI"]%>